version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: cash-api
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - database

  database:
    build: .docker/postgres
    container_name: cash-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cashapi
      - POSTGRES_USER=postgres
